# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_itestdeploy:
     runs-on: ubuntu-16.04
     steps:
     - uses: actions/checkout@v1
     - name: Build and deploy the Docker image
       env:
         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
         APP_NAME: ${{ 'moores-id' }}
       run: |
         cd ./ASPNetCoreLabs/HerokuContainer
         docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
         heroku container:push web -a $APP_NAME
         heroku container:release web -a $APP_NAME
 
